### ISSUE TITLE
SyMBac.phase_contrast_drawing missing in main branch

### ISSUE THREAD

**Issue by kmpape** [georgeoshardo/SyMBac#31]
Hi

I fetched your main branch and tried to run your unit test, but the main branch is missing
`SyMBac.phase_contrast_drawing`
I see that it is available on the legacy branch. Is one supposed to work with the legacy branch?

Thanks,
Idris

PS: 
I have installed SyMBac via venv and pip3.8, which required following additions:
`bin/pip3.8 install pytest`
`bin/pip3.8 install numpy==1.23.5`
`bin/pip3.8 install pyqt5==5.15.9 --config-settings --confirm-license= --verbose`

**Comment by georgeoshardo** [comment]
Sorry - I had missed this issue. Hopefully my reply on your other one has helped. These unit tests will be removed/rewritten in a later commit.
