### ISSUE TITLE
Unit Test Fails

### ISSUE THREAD

**Issue by kmpape** [georgeoshardo/SyMBac#32]
Hello,

I tried to run the test from the legacy branch, and I am obtaining the error below. Any help is greatly appreciated.

Thank you!

---------------------------

Timeseries Properties: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 615.96it/s]
Scene Draw:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 19.32it/s]
/home/XX/workspace_python/symbac_pip/SyMBac/PSF.py:88: RuntimeWarning: invalid value encountered in divide
  kernel1 = 2*jv(1,rr)/(rr)
/home/XX/workspace_python/symbac_pip/SyMBac/PSF.py:91: RuntimeWarning: invalid value encountered in divide
  kernel2 = 2*(R-W)**2/R**2 * jv(1,(R-W)**2/R**2 * rr)/rr
F
======================================================================
FAIL: test_partial_example (__main__.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_phase_contrast_drawing.py", line 87, in test_partial_example
    real_resize, expanded_resized = make_images_same_shape(real_image, convolved, rescale_int=True);
  File "/home/XX/workspace_python/symbac_pip/SyMBac/general_drawing.py", line 329, in make_images_same_shape
    assert real_image.shape[0] < synthetic_image.shape[
AssertionError: Real image has a higher diemsion on axis 0, increase y_border_expansion_coefficient

----------------------------------------------------------------------
Ran 1 test in 2.591s

FAILED (failures=1)

**Comment by kmpape** [comment]
Increasing the coefficient to 20 as suggested makes the assertion error disappear, but the following remains:

Timeseries Properties: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 410.75it/s]
Scene Draw:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 18.84it/s]
/home/XX/workspace_python/symbac_pip/SyMBac/PSF.py:88: RuntimeWarning: invalid value encountered in divide
  kernel1 = 2*jv(1,rr)/(rr)
/home/XX/workspace_python/symbac_pip/SyMBac/PSF.py:91: RuntimeWarning: invalid value encountered in divide
  kernel2 = 2*(R-W)**2/R**2 * jv(1,(R-W)**2/R**2 * rr)/rr
.
----------------------------------------------------------------------
Ran 1 test in 3.489s

OK



Any help is greatly appreciated. Thank you.

**Comment by georgeoshardo** [comment]
Hey, thanks for your interest in this library. The structure of the rest of the library has greatly changed since I wrote that unit-test. I would not expect it to work anymore, and in reality it should be deleted and completely rewritten. I will leave this open as a reminder to eventually do this. You should be able to use the library according to the instructions in the Readthedocs.

**Comment by kmpape** [comment]
Thank you for your answer. In that case, the other issue might be related. I will go through Readthedocs and contribute if possible.
