### ISSUE TITLE
tifffile version

### ISSUE THREAD

**Issue by kmpape** [georgeoshardo/SyMBac#33]
Hi there,

I don't think that setup.py specifies a version for tifffile. With version 2021.10.12, I obtain an error from SyMBac.misc.misc_load_img:

`TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: ‘dtype’, ‘count’, and ‘offsetsize’`

After upgrading it to version 2023.2.3 things work fine.

**Comment by georgeoshardo** [comment]
Thank you, I have bumped the tifffile version in the latest commit.
