### ISSUE TITLE
Dataset from tutorial

### ISSUE THREAD

**Issue by kmpape** [georgeoshardo/SyMBac#36]
Hi @georgeoshardo 

Would it be possible for you to share the file(s) used for the following step in the documentation:

`real_data = tifffile.imread("real_data/trench_0.tif")[:8]`

This would be very helpful, thank you.

**Comment by georgeoshardo** [comment]
Hi Idris, here it is https://www.dropbox.com/scl/fo/se7ivf3t1sl5ffbjwt0td/h?rlkey=924e15dm4cuib5pg7lq7cn3s4&dl=0
