### ISSUE TITLE
Error in convolution

### ISSUE THREAD

**Issue by tauzn-clock** [georgeoshardo/SyMBac#39]
Hello, 

I have been experimenting with the `ColonyRenderer` function. When convolving a simple spot with a generic PSF (with no noise), I realise that the image looks like this.
![image](https://github.com/georgeoshardo/SyMBac/assets/72295649/dcdc2821-6fd0-4379-b053-2f095750c6d6)
Left Image - Original Image intensity
Centre Image - Mask
Right Image - Output Image intensity 

This seems clearly wrong, there are no reasons why the diagonal intensities are at a lower magnitude than the centre pt.

I suspect there might be an error in Line 94 of `renderer.py`. Setting `cuconvolve` with the flag `mode="constant"` gives us the following convolution output.

![image](https://github.com/georgeoshardo/SyMBac/assets/72295649/ac9c6a29-a5a3-4579-a64e-3840925177a9)

This looks much more reasonable

**Comment by georgeoshardo** [comment]
Thank you, this appears to be correct. I will update the convolution function soon and let you know in this issue which commit fixes it :)

**Comment by tauzn-clock** [comment]
Cool I have made a pull request here. [https://github.com/georgeoshardo/SyMBac/pull/40](https://github.com/georgeoshardo/SyMBac/pull/40)

Incidentally, you might have to do it at Line 327 in the same file as well. I am not sure because I have examined this part of the code.

**Comment by georgeoshardo** [comment]
Merged, yes correct, all calls to `cuconvolve` need that argument. I will leave this open until I fix that. I may just redefine `cuconvolve` in the imports to make this the default behaviour.
