### ISSUE TITLE
Scipy convolve doesn't accept mode="constant"

### ISSUE THREAD

**Issue by cmalinmayor** [georgeoshardo/SyMBac#46]
I got the following error when trying to run the Renderer cell in the example jupyter notebook for mother machine lineage output - presumably its because I was trying to run it locally on my mac laptop, and the scipy and cupy convolve signatures are different. I replaced "constant" with "same" in line 57 of the renderer and it ran after that.
I can make a PR, but I wanted to note it down here before I forgot.

> File ~/code/SyMBac/SyMBac/renderer.py:57, in convolve_rescale(image, kernel, rescale_factor, rescale_int)
     36 def convolve_rescale(image, kernel, rescale_factor, rescale_int):
     37     """
     38     Convolves an image with a kernel, and rescales it to the correct size.
     39 
   (...)
     54         The output of the convolution rescale operation
     55     """
---> 57     output = cuconvolve(image, kernel, mode="constant")
     58     # output = output.get()
     59     output = rescale(output, rescale_factor, anti_aliasing=False)
>
> File ~/miniconda3/envs/symbac/lib/python3.8/site-packages/scipy/signal/_signaltools.py:1720, in convolve2d(in1, in2, mode, boundary, fillvalue)
   1717 if _inputs_swap_needed(mode, in1.shape, in2.shape):
   1718     in1, in2 = in2, in1
-> 1720 val = _valfrommode(mode)
   1721 bval = _bvalfromboundary(boundary)
   1722 out = _sigtools._convolve2d(in1, in2, 1, val, bval, fillvalue)
>
> File ~/miniconda3/envs/symbac/lib/python3.8/site-packages/scipy/signal/_signaltools.py:44, in _valfrommode(mode)
     42     return _modedict[mode]
     43 except KeyError as e:
---> 44     raise ValueError("Acceptable mode flags are 'valid',"
     45                      " 'same', or 'full'.") from e
>
> ValueError: Acceptable mode flags are 'valid', 'same', or 'full'.

**Comment by georgeoshardo** [comment]
Thank you, I must have missed this since I never run it without a GPU.

**Comment by georgeoshardo** [comment]
Fixed!
